import pandas as pd
import numpy as np


def build_candidate_features(candidates: pd.DataFrame, interaction_df: pd.DataFrame) -> pd.DataFrame:
    """
    Build ranking features from generated recommendation candidates.
    :param candidates: a candidate DataFrame generated by the retrieval functions
    :param interaction_df:
    :return: a DataFrame containing aggregated ranking features
    """
    feature_df = candidates.copy()

    # Clean missing values
    similarity_columns = ["track_similarity_score", "artist_similarity_score", "vector_similarity_score"]
    for col in similarity_columns:
        feature_df[col] = feature_df[col].fillna(0)
    feature_df["interaction_strength"] = (feature_df["interaction_strength"].fillna(0))

    # Number of different sources that generated each candidate
    source_overlap = (
        feature_df
        .groupby(["user_id", "track_id"])["source"]
        .nunique()
        .rename("n_sources")
        .reset_index())

    # One row per user-track pair
    feature_df = (
        feature_df
        .groupby(["user_id", "track_id"], as_index=False)
        .agg({
            "interaction_strength": "max",
            "track_similarity_score": "max",
            "artist_similarity_score": "max",
            "vector_similarity_score": "max",
        })
        .merge(source_overlap, on=["user_id", "track_id"], how="left"))

    # Global track popularity
    global_interaction_strength = (
        interaction_df
        .groupby("track_id")["interaction_strength"]
        .sum()
        .rename("global_interaction_strength")
        .reset_index()
    )
    feature_df = feature_df.merge(global_interaction_strength, on="track_id", how="left")
    feature_df["global_popularity_missing"] = (feature_df["global_interaction_strength"].isna().astype(int))
    feature_df["global_interaction_strength"] = (feature_df["global_interaction_strength"].fillna(0))
    feature_df["global_interaction_strength_log"] = np.log1p(feature_df["global_interaction_strength"])

    # Combined similarity features
    similarity_columns = ["track_similarity_score", "artist_similarity_score", "vector_similarity_score"]
    feature_df["max_similarity"] = (feature_df[similarity_columns].max(axis=1))
    feature_df["mean_similarity"] = (feature_df[similarity_columns].replace(0, np.nan).mean(axis=1).fillna(0))

    # Number of retrieval methods that supplied similarity evidence
    feature_df["n_similarity_sources"] = (feature_df[similarity_columns] > 0).sum(axis=1)

    # Log-transform interaction strength
    feature_df["interaction_strength_log"] = np.log1p(feature_df["interaction_strength"])
    # Normalize interaction strength within each user
    user_max = (feature_df.groupby("user_id")["interaction_strength_log"].transform("max"))
    feature_df["interaction_strength_normalized"] = np.where(
        user_max > 0, feature_df["interaction_strength_log"] / user_max, 0)

    # Similarity signals
    feature_df["track_signal"] = (feature_df["interaction_strength_normalized"] * feature_df["track_similarity_score"])
    feature_df["artist_signal"] = (feature_df["interaction_strength_normalized"] * feature_df["artist_similarity_score"])
    feature_df["vector_signal"] = (feature_df["interaction_strength_normalized"] * feature_df["vector_similarity_score"])

    return feature_df

    # ranking_features = [
    #     "interaction_strength_log",
    #     "interaction_strength_normalized",
    #
    #     "track_similarity_score",
    #     "artist_similarity_score",
    #     "vector_similarity_score",
    #
    #     "track_signal",
    #     "artist_signal",
    #     "vector_signal",
    #
    #     "max_similarity",
    #     "mean_similarity",
    #
    #     "n_sources",
    #     "n_similarity_sources",
    #
    #     "global_interaction_strength_log",
    #     "global_popularity_missing",
    # ]



